name: subtracker_pro_india
description: A comprehensive subscription management app for Indian users with Firebase integration.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  firebase_storage: ^11.5.6

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9

  # UI & UX
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # Indian Specific
  intl: ^0.19.0
  easy_localization: ^3.0.3
  flutter_local_notifications: ^16.3.0

  # Charts & Analytics
  fl_chart: ^0.65.0

  # Utilities
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  permission_handler: ^11.1.0

  # Indian Payment Integration
  razorpay_flutter: ^1.3.7

  # Additional useful packages
  google_sign_in: ^6.1.6
  pin_code_fields: ^8.0.1
  flutter_slidable: ^3.0.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/animations/
    - assets/translations/

  # fonts:
    # - family: Noto Sans
    #   fonts:
    #     - asset: assets/fonts/NotoSans-Regular.ttf
    #     - asset: assets/fonts/NotoSans-Bold.ttf
    #       weight: 700
    # - family: Noto Sans Devanagari
    #   fonts:
    #     - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
    #     - asset: assets/fonts/NotoSansDevanagari-Bold.ttf
    #       weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FF6B35"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
